# ===========================================
# Site Information Settings
# ===========================================

# Site creation time
since: 2019

# Custom your favicon.ico in `site/source`
favicon: /favicon.ico

# Set feed link (false | default | your feed link)
# false: disable
# default: use `atom.xml`, generator for `hexo-generator-feed`
rss: default

# ===========================================
# Menu Settings
# ===========================================
menu:
  归档: /archives
  关于: /about

# ===========================================
# Widget Settings
# ===========================================
# widget function
# false: disable
# widget_custom: custom your widget
#   title: your widget title
#   content: Add your html code in here. Example: <p>testing...</p>
widget:
  Tags: true
  Categories: true
  Custom: true

widget_custom:
    title: 友情链接
    content: <a href="https://blog.csdn.net/cnyali">廖哥的博客！！！</a> <br> <a href="https://blog.csdn.net/ylsoi">AK王ylsoi的博客！！！</a> <br> <a href="blog.csdn.net/hhaannyyii">RudyGay的博客！！！</a> <br> <a href="blog.csdn.net/qq_35703773">Bzy巨佬博客！！！</a> <br> <a href="https://www.cnblogs.com/LSTete/">Gaystete的博客！！！</a> <br> <a href="https://blog.csdn.net/weixin_42437440">_Sfukin！！！</a> <br> <a href="https://www.cnblogs.com/brunch/">大菜b的博客！！！</a> <br> <a href="https://blog.csdn.net/forever_shi">forever_shi的博客！！！</a> <br>

# MathJax Support
mathjax:
  enable: true
  per_page: true
# ===========================================
# Theme Settings
# ===========================================
# theme styling
# color: Default | Mint Green | Cobalt Blue | Hot Pink | Dark Violet
theme:
  color: Default
  fancybox: false

# ===========================================
# Third Party Services Settings
# ===========================================

# Baidu Analytics
baidu_analytics:
# Google Analytics
google_analytics:

# Duoshuo
duoshuo_shortname:
# Disqus
disqus_shortname:

markdown_it_plus:
  highlight: true
  html: true
  xhtmlOut: true
  breaks: true
  langPrefix:
  linkify: true
  typographer:
  quotes: “”‘’
  plugins:
    - plugin:
        name: markdown-it-katex
        enable: true
    - plugin:
        name: markdown-it-mark
        enable: false

# ===========================================
# Version
# ===========================================
version: 1.1
